# prometheus.yml

global:
  scrape_interval: 5s          # Scrape every 5 seconds (faster for dev/ML pipelines)
  evaluation_interval: 5s      # Evaluate rules every 5 seconds

scrape_configs:
  # Scrape Flask app metrics (your app should expose /metrics on port 5000)
  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:5000']

  # Scrape Pushgateway (used by Jenkins job metrics)
  - job_name: 'pushgateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9091']

# Optional: alerting config (only useful if you run Alertmanager locally)
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

# Optional: load alerting/recording rules
rule_files:
  - "/etc/prometheus/rules/alert_rules.yml"
