groups:
  - name: ml_alerts
    rules:
      - alert: LowModelWeightedScore
        expr: ml_best_model_weighted_score < 0.6
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Best model weighted score dropped below 0.6"
          description: "Best model weighted score is {{ $value }}"

      - alert: HighPredictionErrorRate
        expr: increase(http_requests_total{job="flask_app",status=~"5.."}[5m]) / increase(http_requests_total{job="flask_app"}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High prediction error rate (>5%)"

      - alert: ModelAccuracyDrop
        expr: ml_best_model_score < 0.6
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Model accuracy dropped"
          description: "Best model accuracy is below 85% for 5 minutes."
